### ISSUE TITLE
Format Request

### ISSUE THREAD

**Issue by L11K** [lamdaV/AnimeFeedBot#1]
Hello. 

I don't know if you are accepting requests, but could you change the format? Instead of only the title, having
```
Title
-Episode, time
```
Because as it is right now the bot posts the same title twice if it happens to have two episodes in one day.

Plus, if you could, the option for timezone.

**Comment by lamdav** [comment]
Good point. I hadn't considered the possibility of multiple episodes releasing on the same day. 

I just reworked some of the logic to better handle multiple episode releases. As for your format update request, see the image below. If there are multiple episodes released on the same day, it should look something like
```
show-title
- Ep 1 @ time1
- Ep 2 @ time2
```

![image](https://user-images.githubusercontent.com/11449373/41836473-b2bf47e8-780f-11e8-93a3-61b30bafc8f5.png)

I'll look into updating my simplified command parser to include timezone options.

**Comment by lamdav** [comment]
Timezone should be supported now. 

Commands:
```
-> anime-today America/New_York
```

should give you times in the provided timezone. If none is provided, it will default to `America/Los_Angeles`. You can find the list of supported timezones [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

Along with this update, you can specify interval length and timezones for the `-> update` command.
Interval is now required and must be given in milliseconds. Timezone is optional. 
```
-> update <interval> [TZ]
```

**Comment by L11K** [comment]
Wonderful.

Maybe it would be best if it was sorted by airing time? So when it doesn't get airtime data, the entry is pushed to the bottom with no time there or "N/A". Maybe the TZ should also change the time format, like the USA is Month/Day and other places are Day/Month or Year/Day/Month.
![image](https://user-images.githubusercontent.com/18279534/41881333-62fc8d74-78b9-11e8-89ae-1291f0eb9000.png)

By the way, does it filter or just posts everything? Like Music/Specials/recaps. It filtering recaps would be interesting.

I have more suggestions and will use the feature template and open another issue since this one was already fixed(If you are open to them, of course)

**Comment by lamdav** [comment]
I update the sorting by time and try to see how monthly.moe handles listing with no airtime. My best guess is that they put the datetime stamp for the day with the airing time at 0:00. 

As for locale with date formatting, I can look into it. I can think of a quick and dirty solution but it seems a bit tedious. 

As for filtering, the bot doesn't do any internal filtering other than grabbing anime for the date. Monthly.moe's api doesn't seem to store music with the episode listings; however, specials and recaps are grouped together. I don't think the api returns enough information to determine if it is a recap or special (distinguishing the two).

**Comment by L11K** [comment]
If it was sorted by what is going to air first, then it would be more organized.
Descending Order.  Yeah, I saw that in the API about the specials and thought they would do that.

**Comment by lamdav** [comment]
Here is the new logic for the ordering:
Given 2 shows, `show1` and `show2`, with a list of airing episodes for the given day, `show1` will come before `show2` if all `show1` episodes airing on the given day are before `show2`. vice versa. In the case of a mix (i.e some of `show1` episodes come before and after some of `show2` episodes), the title of the shows will determine the ordering (I don't know when or how often this would occur). For shows with episodes with `0:00`, they will be moved towards the bottom of the list since these have unknown airtime and will be displayed as `???`. 

As for locale, I decided to not try to update the displaying order of the date. The abbreviation of the month and 4 digits for the year makes it pretty clear if it was a confusion issue.

**Comment by L11K** [comment]
I mentioned the time format because of completion/consistency since it provides timezone option and time zones have different time formats, I thought it would be the logical next step.

**Comment by lamdav** [comment]
@L11K 

I am going to create a new issue. If you would like to do this, feel free to do so and submit a PR.
