### ISSUE TITLE
Date Formatting Based on Timezone

### ISSUE THREAD

**Issue by lamdav** [lamdaV/AnimeFeedBot#2]
**Describe the solution you'd like**
Given a timezone (i.e. America/Los_Angeles), modify the date format that is suitable for that region
(America => MM/DD/YYYY) and send it with the updates.

**Comment by shoutoutloud** [comment]
Hi. Can I have a look into it ?

**Comment by L11K** [comment]
According to #1 , you can.

**Comment by shoutoutloud** [comment]
Hi.I think our only option is to create our own API which returns the date format from a entered location , as I tried to find any such API or NPM module but  I did not came through any.What are your thoughts?

**Comment by lamdav** [comment]
When I was taking a look at this, one of the hacky solutions was to have a mapping prefix to date format. For example: 
```javascript
const TIMEZONE_TO_DATE_FORMAT = {'America': 'MMMM Do YYYY (zz)'}
```

So, something like `America/Los_Angeles` or `America/New_York` gets mapped to the same format. 

Alternatively, I think what you proposed works well. We can have a default formatting and allow the users to specify their own date setting.

Let me know what you decide to go with.
Just a heads up, I am a bit busy this week and may not be able to respond as quickly as I would like to.

**Comment by shoutoutloud** [comment]
Are you thinking something like this `America/Los_Angeles DMY` ,where `DMY` `MDY` `YMD` would be specifying different date format ( MDY => MM/DD/YYYY ).

**Comment by lamdav** [comment]
@shoutoutloud 

yep. My example above has the `moment` datetime formatting. I mentioned prefixed to avoid redundant mappings.

**Comment by lamdav** [comment]
#3
